#!/bin/sh

#SBATCH --job-name=reproduce_collect_result_every_2048_steps
#SBATCH --output=%a_output.slurm

#SBATCH --time=7-00:00:00
#SBATCH --cpus-per-task=3
#SBATCH --mem=10000mb
#SBATCH --mail-type=END,FAIL,REQUEUE,STAGE_OUT
#SBATCH --mail-user=qhv200@nyu.edu
#SBATCH --partition=mujoco
#SBATCH --qos=h480

#SBATCH --array=0-99

source activate /gpfsnyu/scratch/qhv200/conda_envs/mujoco1.5_py352

cd /gpfsnyu/scratch/qhv200/trust_region_research_atari/reproduce_collect_result_every_2048_steps/

OMP_NUM_THREADS=3 MPLBACKEND=Agg python main_exp.py